### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by pfilbin90** [zeichensatz/SynologyPhotosAPI#1]
I have an issue with my photos where the date is part of the title, such as "IMG_20130407.jpg" but the metadata for these photos are nonexistent.  I am wanting to update the metadata so that they show up properly in the Synology photos timeline.  Is there a way to use the Synology API to add the date time metadata somehow from the title?

**Comment by zeichensatz** [comment]
The API will probably not provide you with more features than which can be used within Synology Photos.
This documentation is at the early beginning. You might improve it.

Refering to your problem: Aren't you able to add a date/time to the photo in Synology Photos? Doesn't Synology Photos using the creation date?
I just checked, that at least you're able to edit the timestamp of a photo in Synology Photos and it then will be properly listed in the timeline view. 
If you are not able to add a timestamp within Synology Photos, then you might consider other tools to edit the metadata of the files, for example ExifTool. With ExifTool you even might be able to create a script to get the date from your filesname and write it to the exif data.
